# Generated by Django 5.0.6 on 2026-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="page_map",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
